### ISSUE TITLE
PHP 7.1 with nginx

### ISSUE THREAD

**Issue by ashikkalavadiya** [multidots/php7-ci#1]
Fast CGI is always a better choice :) Let me know if you want such image then i can create PR here.

**Comment by solanki-ankit** [comment]
Yeah, your PR is welcome :)

**Comment by ashikkalavadiya** [comment]
PR created!

**Comment by narendravaghela** [comment]
@ashikkalavadiya Please check my comment on your PR - https://github.com/multidots/php7-ci/pull/2
